# Generated by Django 4.2.2 on 2023-06-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hotel_media/')),
                ('has_perking', models.BooleanField(default=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_pool', models.BooleanField(choices=[(1, 'Да'), (2, 'Нет')], default='Нет')),
                ('stars', models.IntegerField(choices=[(1, '1 звезд'), (2, '2 звезд'), (3, '3 звезд'), (4, '4 звезд'), (5, '5 звезд')], default=1)),
                ('address', models.CharField(max_length=255)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.city')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.IntegerField(choices=[(1, 'на два человека'), (2, 'на два и более человек'), (3, 'на четыре и более человек')], default=1)),
                ('description', models.TextField()),
                ('hotel_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel_media')),
            ],
        ),
    ]
