# Generated by Django 4.2.2 on 2023-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_media',
            name='has_pool',
            field=models.IntegerField(choices=[(1, 'Да'), (2, 'Нет')], default='Нет'),
        ),
    ]
