# Generated by Django 4.2.2 on 2023-06-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_has_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmenttype',
            name='choose',
        ),
        migrations.RemoveField(
            model_name='apartmenttype',
            name='description',
        ),
        migrations.AddField(
            model_name='hotel_media',
            name='room',
            field=models.IntegerField(choices=[(1, 'на два человека'), (2, 'на два и более человек'), (3, 'на четыре и более человек')], default=1),
        ),
    ]
