# Generated by Django 4.2.2 on 2023-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_apartmenttype_choose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_media',
            name='room',
        ),
        migrations.AddField(
            model_name='apartmenttype',
            name='room',
            field=models.IntegerField(choices=[(1, 'на два человека'), (2, 'на два и более человек'), (3, 'на четыре и более человек')], default=1),
        ),
    ]
