# Generated by Django 4.2.2 on 2023-06-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_remove_hotel_room_apartmenttype_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apartment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.apartmenttype')),
            ],
        ),
    ]
