# Generated by Django 4.2.2 on 2023-06-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmenttype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
